### PR TITLE
fail fast: refuse to start server with invalid option systemProperties

### PR DESCRIPTION
**Pull request by hennr**
This PR fixes some jshint warnings, restructures one test a bit and finally checks if systemProperties is used.
If so, honoring the fail fast philosophy, the server refuses to start and prints an error regarding the renamed option.

### CODE REVIEW

**Comment by jamesdbloom** [comment]
Can you please resolve the merge conflicts then I can merge the PR, thanks

**Comment by hennr** [comment]
@jamesdbloom go.

**Comment by hennr** [comment]
I invested quite some time finding the error, fixing it, preparing this (and some other) PR, rebasing the master as you merged a different PR first and now I am waiting again for my changes to get into master.
@jamesdbloom this is frustrating and does absolotely not lead to another PR from my side. Could you please merge this one and let us be done with it?

**Comment by jamesdbloom** [comment]
I've merged it now, sorry it took so long but I have a lot on at the moment.

**Pull request merged**
